src/main/java/edu/ufrn/imd/exemploweb/model/Cliente.java
package edu.ufrn.imd.exemploweb.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;

import edu.ufrn.imd.exemploweb.componentes.ModeloGenerics;

@Entity
public class Cliente extends Pessoa implements ModeloGenerics{

	@Column
	private String cartaoFidelidade;
	@Column
	private String credito;
	
	@OneToMany(mappedBy="cliente")
	List<Conta> contas;
	
	public Cliente() {
		super();
		contas = new ArrayList<Conta>();
	}
	public Cliente(String nome, String cpf, String endereco, String telefone) {
		super(nome, cpf, endereco, telefone);
		contas = new ArrayList<Conta>();
	}
	
	public String getCartaoFidelidade() {
		return cartaoFidelidade;
	}
	public void setCartaoFidelidade(String cartaoFidelidade) {
		this.cartaoFidelidade = cartaoFidelidade;
	}
	public String getCredito() {
		return credito;
	}
	public void setCredito(String credito) {
		this.credito = credito;
	}

	public List<Conta> getContas() {
		return contas;
	}
	public void setContas(List<Conta> contas) {
		this.contas = contas;
	}
	
	public int getTotalContasAtivas() {
		int resultado = 0;
		for (Conta conta : contas) {
				if(!conta.isPago())
					resultado ++;
		}
		return resultado;
	}
	
	public double getSubTotal() {
		double resultado = 0;
		for (Conta conta : contas) {
			resultado += conta.getSubTotal();
		}
		return resultado;
	}
	
}

src/main/java/edu/ufrn/imd/exemploweb/model/ItemConta.java
package edu.ufrn.imd.exemploweb.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import edu.ufrn.imd.exemploweb.componentes.ModeloGenerics;

@Entity
public class ItemConta implements ModeloGenerics{

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int id;
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="conta_id")
	private Conta conta;
	@ManyToOne
	@JoinColumn(name="item_id")
	private Item item;
	@Column(nullable=false)
	private int quantidade;
	
	public ItemConta() {
		// TODO Auto-generated constructor stub
		item = new Item();
		conta = new Conta();
	}
	
	@Override
	public boolean equals(Object obj) {
		if(obj == null)
			return false;
		if(obj instanceof ItemConta)
			if(((ItemConta)obj).getId() == id)
				return true;
		
		return false;
	}
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public Conta getConta() {
		return conta;
	}
	public void setConta(Conta conta) {
		this.conta = conta;
	}
	public Item getItem() {
		return item;
	}
	public void setItem(Item item) {
		this.item = item;
	}
	public int getQuantidade() {
		return quantidade;
	}
	public void setQuantidade(int quantidade) {
		this.quantidade = quantidade;
	}
	
	public double getValorTotal(){
		double valor = item != null ? quantidade*item.getValor() : 0;
		return valor;
	}

}

src/main/java/edu/ufrn/imd/exemploweb/webui/ClienteBean.java
package edu.ufrn.imd.exemploweb.webui;

import java.io.Serializable;
import java.util.ArrayList;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIViewRoot;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;

import edu.ufrn.imd.exemploweb.componentes.Aplicacao;
import edu.ufrn.imd.exemploweb.componentes.Mensagem;
import edu.ufrn.imd.exemploweb.dao.HibernateBDException;
import edu.ufrn.imd.exemploweb.model.Cliente;
import edu.ufrn.imd.exemploweb.service.ClienteService;

@ManagedBean
@SessionScoped
public class ClienteBean extends GenericBean<Cliente> implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Mensagem mensagem = new Mensagem();
	
//	private List<Cliente> listaClientes = new ArrayList<Cliente>();
	
	
	public ClienteBean() {
		// TODO Auto-generated constructor stub
	
		setService(new ClienteService());
		super.setListaItens(new ArrayList<Cliente>());
		super.setItemSelecionado(new Cliente());
		super.setAplicacao(Aplicacao.getInstance());
		setNomeSistema(getAplicacao().getInstance().getNomeSistema());
		setVersaoSistema( getAplicacao().getInstance().getVersaoSistema());
		recarregarLista();
	}
	
	public void selecionarCliente(ActionEvent e){

	}
	

	public void salvar(ActionEvent e) {
		FacesMessage.Severity tipoMsg = FacesMessage.SEVERITY_INFO;
		
		try {
			setItemSelecionado(new Cliente());
			getService().create(getItemSelecionado());
			
			switch(getService().getMensagem().getCodigo()) {
				case 1:
					tipoMsg = FacesMessage.SEVERITY_ERROR;
					break;
				case 2 :
					tipoMsg = FacesMessage.SEVERITY_WARN;
					break;
				default:
					tipoMsg = FacesMessage.SEVERITY_INFO;
			}
		}
		catch(HibernateBDException dbe) {
			tipoMsg = FacesMessage.SEVERITY_ERROR;
		}
		catch(Exception ex) {
			tipoMsg = FacesMessage.SEVERITY_ERROR;
		}
		finally {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(tipoMsg, getService().getMensagem().getConteudo()
					, getService().getMensagem().getConteudo()));
			recarregarLista();			
		}
	}
	public void alterar(ActionEvent e) {
		
		FacesMessage.Severity tipoMsg = FacesMessage.SEVERITY_INFO;

		try {
			getService().update(getItemSelecionado());
		
			switch(getService().getMensagem().getCodigo()) {
				case 1:
					tipoMsg = FacesMessage.SEVERITY_ERROR;
					break;
				case 2 :
					tipoMsg = FacesMessage.SEVERITY_WARN;
					break;
				default:
					tipoMsg = FacesMessage.SEVERITY_INFO;
			}
		}
		catch(HibernateBDException dbe) {
			tipoMsg = FacesMessage.SEVERITY_ERROR;
		}
		catch(Exception ex) {
			tipoMsg = FacesMessage.SEVERITY_ERROR;
		}
		finally {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(tipoMsg, getService().getMensagem().getConteudo()
					, getService().getMensagem().getConteudo()));
			recarregarLista();			
		}
	}
	
	public void excluir(ActionEvent e) {
		
		FacesMessage.Severity tipoMsg = FacesMessage.SEVERITY_INFO;
		try {
			getService().delete(getItemSelecionado());
			switch(getService().getMensagem().getCodigo()) {
				case 1:
					tipoMsg = FacesMessage.SEVERITY_ERROR;
					break;
				case 2 :
					tipoMsg = FacesMessage.SEVERITY_WARN;
					break;
				default:
					tipoMsg = FacesMessage.SEVERITY_INFO;
			}
			
		}
		catch(HibernateBDException dbe) {
			tipoMsg = FacesMessage.SEVERITY_ERROR;
		}
		catch(Exception ex) {
			tipoMsg = FacesMessage.SEVERITY_ERROR;
		}
		finally {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(tipoMsg, "Erro hibernate "+ getService().getMensagem().getConteudo()
					, "Erro hibernate "+ getService().getMensagem().getConteudo()));
			recarregarLista();			
		}
	
	}
	
	private void recarregarLista() {
		setListaItens(getService().findAll());
	}
	
	public Mensagem getMensagem() {
		return mensagem;
	}
	public void setMensagem(Mensagem mensagem) {
		this.mensagem = mensagem;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
	
}

src/main/java/edu/ufrn/imd/exemploweb/webui/ContaBean.java
package edu.ufrn.imd.exemploweb.webui;

import java.io.Serializable;
import java.util.ArrayList;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;

import edu.ufrn.imd.exemploweb.componentes.Aplicacao;
import edu.ufrn.imd.exemploweb.componentes.Mensagem;
import edu.ufrn.imd.exemploweb.dao.HibernateBDException;
import edu.ufrn.imd.exemploweb.model.Conta;
import edu.ufrn.imd.exemploweb.service.ContaService;

@ManagedBean
@SessionScoped
public class ContaBean extends GenericBean<Conta> implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Mensagem mensagem = new Mensagem();
	
	public ContaBean() {
		// TODO Auto-generated constructor stub
	
		setService(new ContaService());
		super.setListaItens(new ArrayList<Conta>());
		super.setItemSelecionado(new Conta());
		super.setAplicacao(Aplicacao.getInstance());
		setNomeSistema(getAplicacao().getInstance().getNomeSistema());
		setVersaoSistema( getAplicacao().getInstance().getVersaoSistema());
		recarregarLista();
	}
	
	public void selecionarConta(ActionEvent e){

	}
	
	public void salvar(ActionEvent e) {
		FacesMessage.Severity tipoMsg = FacesMessage.SEVERITY_INFO;
		
		try {
			Conta novoConta = new Conta();
//			novoConta.setDescricao(getItemSelecionado().getDescricao());
//			novoConta.setValor(getItemSelecionado().getValor());
//			setContaSelecionado(novoConta);
//			getService().create(getItemSelecionado());
//			
//			switch(getService().getMensagem().getCodigo()) {
//				case 1:
//					tipoMsg = FacesMessage.SEVERITY_ERROR;
//					break;
//				case 2 :
//					tipoMsg = FacesMessage.SEVERITY_WARN;
//					break;
//				default:
//					tipoMsg = FacesMessage.SEVERITY_INFO;
//			}
		}
		catch(HibernateBDException dbe) {
			tipoMsg = FacesMessage.SEVERITY_ERROR;
		}
		catch(Exception ex) {
			tipoMsg = FacesMessage.SEVERITY_ERROR;
		}
		finally {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(tipoMsg, getService().getMensagem().getConteudo()
					, getService().getMensagem().getConteudo()));
			recarregarLista();			
		}
	}
	public void alterar(ActionEvent e) {
		
		FacesMessage.Severity tipoMsg = FacesMessage.SEVERITY_INFO;

		try {
			getService().update(getItemSelecionado());
		
			switch(getService().getMensagem().getCodigo()) {
				case 1:
					tipoMsg = FacesMessage.SEVERITY_ERROR;
					break;
				case 2 :
					tipoMsg = FacesMessage.SEVERITY_WARN;
					break;
				default:
					tipoMsg = FacesMessage.SEVERITY_INFO;
			}
		}
		catch(HibernateBDException dbe) {
			tipoMsg = FacesMessage.SEVERITY_ERROR;
		}
		catch(Exception ex) {
			tipoMsg = FacesMessage.SEVERITY_ERROR;
		}
		finally {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(tipoMsg, getService().getMensagem().getConteudo()
					, getService().getMensagem().getConteudo()));
			recarregarLista();			
		}
	}
	public void excluir(ActionEvent e) {
		
		FacesMessage.Severity tipoMsg = FacesMessage.SEVERITY_INFO;
		try {
			getService().delete(getItemSelecionado());

			switch(getService().getMensagem().getCodigo()) {
				case 1:
					tipoMsg = FacesMessage.SEVERITY_ERROR;
					break;
				case 2 :
					tipoMsg = FacesMessage.SEVERITY_WARN;
					break;
				default:
					tipoMsg = FacesMessage.SEVERITY_INFO;
			}
			
		}
		catch(HibernateBDException dbe) {
			tipoMsg = FacesMessage.SEVERITY_ERROR;
		}
		catch(Exception ex) {
			tipoMsg = FacesMessage.SEVERITY_ERROR;
		}
		finally {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(tipoMsg, "Erro hibernate "+ getService().getMensagem().getConteudo()
					, "Erro hibernate "+ getService().getMensagem().getConteudo()));
			recarregarLista();			
		}
	
	}
	
	private void recarregarLista() {
		setListaItens(getService().findAll());
	}
	
	public Mensagem getMensagem() {
		return mensagem;
	}
	public void setMensagem(Mensagem mensagem) {
		this.mensagem = mensagem;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}
}

src/main/java/edu/ufrn/imd/exemploweb/webui/GarconBean.java
package edu.ufrn.imd.exemploweb.webui;

import java.io.Serializable;
import java.util.ArrayList;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;

import edu.ufrn.imd.exemploweb.componentes.Aplicacao;
import edu.ufrn.imd.exemploweb.componentes.Mensagem;
import edu.ufrn.imd.exemploweb.dao.HibernateBDException;
import edu.ufrn.imd.exemploweb.model.Garcon;
import edu.ufrn.imd.exemploweb.service.GarconService;

@ManagedBean
@SessionScoped
public class GarconBean extends GenericBean<Garcon> implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	
	private Mensagem mensagem = new Mensagem();
	
	public GarconBean() {
		// TODO Auto-generated constructor stub
	
		setService(new GarconService());
		super.setListaItens(new ArrayList<Garcon>());
		super.setItemSelecionado(new Garcon());
		super.setAplicacao(Aplicacao.getInstance());
		setNomeSistema(getAplicacao().getInstance().getNomeSistema());
		setVersaoSistema( getAplicacao().getInstance().getVersaoSistema());
		recarregarLista();
	}
	
	public void selecionarGarcon(ActionEvent e){

	}
	
	public void salvar(ActionEvent e) {
		FacesMessage.Severity tipoMsg = FacesMessage.SEVERITY_INFO;
		
		try {
			Garcon novoGarcon = new Garcon();
			novoGarcon.setNome(getItemSelecionado().getNome());
			novoGarcon.setCpf(getItemSelecionado().getCpf());
			setItemSelecionado(novoGarcon);
			getService().create(getItemSelecionado());
			
			switch(getService().getMensagem().getCodigo()) {
				case 1:
					tipoMsg = FacesMessage.SEVERITY_ERROR;
					break;
				case 2 :
					tipoMsg = FacesMessage.SEVERITY_WARN;
					break;
				default:
					tipoMsg = FacesMessage.SEVERITY_INFO;
			}
		}
		catch(HibernateBDException dbe) {
			tipoMsg = FacesMessage.SEVERITY_ERROR;
		}
		catch(Exception ex) {
			tipoMsg = FacesMessage.SEVERITY_ERROR;
		}
		finally {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(tipoMsg, getService().getMensagem().getConteudo()
					, getService().getMensagem().getConteudo()));
			recarregarLista();			
		}
	}
	public void alterar(ActionEvent e) {
		
		FacesMessage.Severity tipoMsg = FacesMessage.SEVERITY_INFO;

		try {
			getService().update(getItemSelecionado());
		
			switch(getService().getMensagem().getCodigo()) {
				case 1:
					tipoMsg = FacesMessage.SEVERITY_ERROR;
					break;
				case 2 :
					tipoMsg = FacesMessage.SEVERITY_WARN;
					break;
				default:
					tipoMsg = FacesMessage.SEVERITY_INFO;
			}
		}
		catch(HibernateBDException dbe) {
			tipoMsg = FacesMessage.SEVERITY_ERROR;
		}
		catch(Exception ex) {
			tipoMsg = FacesMessage.SEVERITY_ERROR;
		}
		finally {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(tipoMsg, getService().getMensagem().getConteudo()
					, getService().getMensagem().getConteudo()));
			recarregarLista();			
		}
	}
	public void excluir(ActionEvent e) {
		
		FacesMessage.Severity tipoMsg = FacesMessage.SEVERITY_INFO;
		try {
			getService().delete(getItemSelecionado());
	//		setItemSelecionado(new Garcon());
			switch(getService().getMensagem().getCodigo()) {
				case 1:
					tipoMsg = FacesMessage.SEVERITY_ERROR;
					break;
				case 2 :
					tipoMsg = FacesMessage.SEVERITY_WARN;
					break;
				default:
					tipoMsg = FacesMessage.SEVERITY_INFO;
			}
			
		}
		catch(HibernateBDException dbe) {
			tipoMsg = FacesMessage.SEVERITY_ERROR;
		}
		catch(Exception ex) {
			tipoMsg = FacesMessage.SEVERITY_ERROR;
		}
		finally {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(tipoMsg, "Erro hibernate "+ getService().getMensagem().getConteudo()
					, "Erro hibernate "+ getService().getMensagem().getConteudo()));
			recarregarLista();			
		}
	
	}
	
	private void recarregarLista() {
		setListaItens(getService().findAll());
	}
	
	public Mensagem getMensagem() {
		return mensagem;
	}
	public void setMensagem(Mensagem mensagem) {
		this.mensagem = mensagem;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
	
}

src/main/java/edu/ufrn/imd/exemploweb/webui/GenericBean.java
package edu.ufrn.imd.exemploweb.webui;

import java.util.List;

import javax.faces.event.ActionEvent;

import edu.ufrn.imd.exemploweb.componentes.Aplicacao;
import edu.ufrn.imd.exemploweb.componentes.ModeloGenerics;
import edu.ufrn.imd.exemploweb.service.GenericService;

public abstract class GenericBean <T extends ModeloGenerics>{

	private GenericService<T> service;
	private T itemSelecionado;
	private List<T> listaItens;
	private Aplicacao aplicacao;
	private String versaoSistema;
	private String nomeSistema;
	
	public GenericService<T> getService() {
		return service;
	}
	
	public void setService(GenericService<T> service) {
		this.service = service;
	}	

	public abstract void salvar(ActionEvent e);
	public abstract void alterar(ActionEvent e);
	public abstract void excluir(ActionEvent e);
	
	public T getItemSelecionado() {
		return itemSelecionado;
	}

	public void setItemSelecionado(T itemSelecionado) {
		this.itemSelecionado = itemSelecionado;
	}

	public List<T> getListaItens() {
		return listaItens;
	}

	public void setListaItens(List<T> listaItens) {
		this.listaItens = listaItens;
	}

	public Aplicacao getAplicacao() {
		return aplicacao;
	}

	public void setAplicacao(Aplicacao aplicacao) {
		this.aplicacao = aplicacao;
	}

	public String getVersaoSistema() {
		return versaoSistema;
	}

	public void setVersaoSistema(String versaoSistema) {
		this.versaoSistema = versaoSistema;
	}

	public String getNomeSistema() {
		return nomeSistema;
	}

	public void setNomeSistema(String nomeSistema) {
		this.nomeSistema = nomeSistema;
	}

}

src/main/java/edu/ufrn/imd/exemploweb/webui/MenuPrincipalBean.java
package edu.ufrn.imd.exemploweb.webui;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.io.Serializable;

@ManagedBean
//@SessionScoped
public class MenuPrincipalBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private String name;

	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
}

src/main/webapp/cliente.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"  
	  xmlns:f="http://java.sun.com/jsf/core" 
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      >
    
   	<ui:composition template="templates/template-principal.xhtml">
	    <ui:define name="cabecalho">
			Menu cliente
		</ui:define>
   	<ui:define name="corpo">
   		
   		<h2>Lista de clientes</h2>
    	
    	<h:dataTable value="#{clienteBean.listaItens}" styleClass="tabela-crud" var="cliente"  rendered="#{not empty clienteBean.listaItens}">
    		<h:column>
	    		<f:facet name="header">#</f:facet>
	    		#{cliente.id}
	    	</h:column>
	    	<h:column>
	    		<f:facet name="header">nome</f:facet>
	    		#{cliente.nome}
	    	</h:column>
	    	<h:column>
	    		<f:facet name="header">cpf</f:facet>
	    		#{cliente.cpf}
	    	</h:column>
	    	<h:column>
	    		<f:facet name="header">SubTotal(Em R$)</f:facet>
	    		<h:outputText value="#{cliente.subTotal}">
	    			<f:convertNumber pattern="#0.00" />
	    		</h:outputText>
	    	</h:column>
	    	<h:column>
	    		<f:facet name="header">selecionar</f:facet>
	    		<h:form>
		    		<h:commandButton value="Selecionar" type="submit" actionListener="#{clienteBean.selecionarCliente}">
		    			<f:setPropertyActionListener target="#{clienteBean.itemSelecionado}" value="#{cliente}" />
		    		</h:commandButton>
	    		</h:form>
	    	</h:column>
    	</h:dataTable>
 
    	<h2>Cliente  (#{clienteBean.itemSelecionado.id})</h2>
    	<h:form>
    	   <h:message for="clienteCPF" errorClass="msg-erro" infoClass="msg-info" warnClass="msg-warn"/>
    	   
    	   <h:panelGrid columns="2" styleClass="grid-formulario">
	    	   <h:outputText value="Nome" />
	    	   <h:inputText value="#{clienteBean.itemSelecionado.nome}" />
	    	   <h:outputText value="CPF" /> 
	    	   <h:inputText id="clienteCPF" value="#{clienteBean.itemSelecionado.cpf}" >
	    	   		<f:validator validatorId="validatorCPF"/>
	    	   </h:inputText>
    	   </h:panelGrid>
    	   
    	    <h:panelGrid columns="3" styleClass="grid-formulario">
	    	   <h:commandButton value="Salvar" type="submit" actionListener="#{clienteBean.salvar}"></h:commandButton>
	    	   <h:commandButton value="Alterar" type="submit" actionListener="#{clienteBean.alterar}"></h:commandButton>
	    	   <h:commandButton value="Excluir" type="submit" actionListener="#{clienteBean.excluir}"></h:commandButton>
    	   </h:panelGrid>
    	   
    	</h:form>
   	</ui:define>
   
   	<ui:define name="footer"><h:outputText value="#{clienteBean.nomeSistema} (Versão #{clienteBean.versaoSistema})" /></ui:define>
   </ui:composition>

</html>

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"      
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
	
	<ui:composition template="templates/template-principal.xhtml"> 
    	<ui:define name="corpo">   		
   			<h2>Bem vindo ao sistema Bar Esolha uma da opções no menu acima</h2>
		</ui:define>
	</ui:composition>
</html>

src/main/webapp/mesa.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"  
	  xmlns:f="http://java.sun.com/jsf/core" 
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      >
    
   	<ui:composition template="templates/template-principal.xhtml">
	    <ui:define name="cabecalho">
			Menu mesa
		</ui:define>
   	<ui:define name="corpo">
   		
   		<h2>Lista de Mesas</h2>
    	
    	<h:dataTable value="#{mesaBean.listaItens}" styleClass="tabela-crud" var="mesa"  rendered="#{not empty mesaBean.listaItens}">
    		<h:column>
	    		<f:facet name="header">#</f:facet>
	    		#{mesa.id}
	    	</h:column>
	    	<h:column>
	    		<f:facet name="header">Número</f:facet>
	    		#{mesa.numero}
	    	</h:column>
	    	<h:column>
	    		<f:facet name="header">Contas em aberto</f:facet>
	    		#{mesa.totalContasAtivas}
	    	</h:column>
	    	<h:column>
	    		<f:facet name="header">SubTotal (Em R$)</f:facet>
	    		<h:outputText value="#{mesa.subTotal}">
	    			<f:convertNumber pattern="#0.00" />
	    		</h:outputText> 
	    	</h:column>
	    	<h:column>
	    		<f:facet name="header">selecionar</f:facet>
	    		<h:form>
		    		<h:commandButton value="Selecionar" type="submit" actionListener="#{mesaBean.selecionarMesa}">
		    			<f:setPropertyActionListener target="#{mesaBean.itemSelecionado}" value="#{mesa}" />
		    		</h:commandButton>
	    		</h:form>
	    	</h:column>
    	</h:dataTable>
 
    	<h2>Mesa  (#{mesaBean.itemSelecionado.id})</h2>
    	<h:form>
    	   
    	   <h:panelGrid columns="2" styleClass="grid-formulario">
	    	   <h:outputText value="Número" />
	    	   <h:inputText value="#{mesaBean.itemSelecionado.numero}" />
    	   </h:panelGrid>
    	   
    	    <h:panelGrid columns="3" styleClass="grid-formulario">
	    	   <h:commandButton value="Salvar" type="submit" actionListener="#{mesaBean.salvar}"></h:commandButton>
	    	   <h:commandButton value="Alterar" type="submit" actionListener="#{mesaBean.alterar}"></h:commandButton>
	    	   <h:commandButton value="Excluir" type="submit" actionListener="#{mesaBean.excluir}"></h:commandButton>
    	   </h:panelGrid>
    	   
    	</h:form>
   	</ui:define>
   	<ui:define name="footer"><h:outputText value="#{mesaBean.nomeSistema} (Versão #{mesaBean.versaoSistema})" /></ui:define>
   </ui:composition>

</html>